build:
  image: default-jammy
  environment:
        php: 8.3.13
        node: 20.18.1
  nodes:
    analysis:
      tests:
        override:
          - command: php-scrutinizer-run
            idle_timeout: 1000

