build:
  dependencies:
    pre:
      - wget http://ftp.gnu.org/gnu/libc/glibc-2.28.tar.gz
      - tar -xvzf glibc-2.28.tar.gz
      - cd glibc-2.28 && mkdir build && cd build
      - ../configure --prefix=/opt/glibc-2.28
      - make -j$(nproc)
      - make install
      - export LD_LIBRARY_PATH=/opt/glibc-2.28/lib:$LD_LIBRARY_PATH
  image: default-bionic
  environment:
        php: 8.3.13
        node: 20.18.1
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
